#!/bin/bash

set -euo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/scripts"

main() {
  echo "================================"
  echo "   Desktop Setup Script"
  echo "================================"
  echo ""

  echo ">>> Running Swap and memory tuning setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-swap.sh"
  echo ""
  echo "✓ Swap setup completed"
  echo ""

  echo ">>> Running Timeshift setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-timeshift.sh"
  echo ""
  echo "✓ Timeshift setup completed"
  echo ""

  echo ">>> Running Debian backports kernel setup..."
  echo ""
  bash "$SCRIPTS_DIR/debian/setup-kernel.sh"
  echo ""
  echo "✓ Debian backports kernel setup completed"
  echo ""

  echo ">>> Running Docker setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-docker.sh"
  echo ""
  echo "✓ Docker setup completed"
  echo ""

  echo ">>> Running Flatpak setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-flatpak.sh"
  echo ""
  echo "✓ Flatpak setup completed"
  echo ""

  echo ">>> Running Firewall setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-firewall.sh"
  echo ""
  echo "✓ Firewall setup completed"
  echo ""

  echo ">>> Running Browsers setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-browsers.sh"
  echo ""
  echo "✓ Browsers setup completed"
  echo ""

  echo ">>> Running DBeaver setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-dbeaver.sh"
  echo ""
  echo "✓ DBeaver setup completed"
  echo ""

  echo ">>> Running Discord setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-discord.sh"
  echo ""
  echo "✓ Discord setup completed"
  echo ""

  echo ">>> Running Telegram setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-telegram.sh"
  echo ""
  echo "✓ Telegram setup completed"
  echo ""

  echo ">>> Running Fonts setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-fonts.sh"
  echo ""
  echo "✓ Fonts setup completed"
  echo ""

  echo ">>> Running Gitflow setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-gitflow.sh"
  echo ""
  echo "✓ Gitflow setup completed"
  echo ""

  echo ">>> Running Golang setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-go.sh"
  echo ""
  echo "✓ Golang setup completed"
  echo ""

  echo ">>> Running NVM/Node setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-nvm.sh"
  echo ""
  echo "✓ NVM/Node setup completed"
  echo ""

  echo ">>> Running Kitty terminal setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-kitty.sh"
  echo ""
  echo "✓ Kitty terminal setup completed"
  echo ""

  echo ">>> Running Lazygit setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-lazygit.sh"
  echo ""
  echo "✓ Lazygit setup completed"
  echo ""

  echo ">>> Running Lazydocker setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-lazydocker.sh"
  echo ""
  echo "✓ Lazydocker setup completed"
  echo ""

  echo ">>> Running Neovim setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-neovim.sh"
  echo ""
  echo "✓ Neovim setup completed"
  echo ""

  echo ">>> Running Default applications setup..."
  echo ""
  bash "$SCRIPTS_DIR/setup-default-apps.sh"
  echo ""
  echo "✓ Default applications setup completed"
  echo ""

  echo "================================"
  echo "   Setup Completed Successfully!"
  echo "================================"
}

main "$@"
